from Tkinter import *
root5=Tk()
root5.geometry('800x600')
root5.configure(bg='red')
a=PhotoImage(file='C:\Users\win\Desktop\PhoneBook\photo.gif')
Label(root5,image=a).grid(row=4,column=1)
Label(root5,text='Project Title:PhoneBook',bg='red',font=' times 20 bold').grid(row=0,column=0)
Label(root5,text='make mouse movement over this screen to close',bg='yellow',fg='dark red',font=('Ariel')).grid(row=10,column=1)
Label(root5,text='Project of Python and database',bg='red',font='times 20 bold').grid(row=1,column=1)
Label(root5,text='Subject Name:Advanced Programming-I',fg='yellow',bg='red',font='times 15 bold').grid(row=2,column=1)
Label(root5,text='Guide By:Dr.Mahesh Kumar and Dr.Nilesh Kumar Patel',fg='green',bg='red',font='times 15 bold').grid(row=3,column=1)
Label(root5,text='Developed By:RAM PRATAP SINGH ',bg='red',font='times 15 bold',fg='blue').grid(row=5,column=1)
Label(root5,text='Eno.181B268',font='times 15 bold',bg='red',fg='blue').grid(row=6,column=1)
Label(root5,text='Batch-B6',bg='red',font='times 15 bold',fg='blue').grid(row=7,column=1)
Label(root5,text='Phone No:9149286521',bg='red',font='times 15 bold',fg='blue').grid(row=8,column=1)
Label(root5,text='Email Id:rampratapsingh1331@gmail.com',bg='red',font='times 15 bold',fg='blue').grid(row=9,column=1)
def close(e=1):
    root5.destroy()
root5.bind('<Motion>',close)
root5.mainloop()
